[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
padding.x = 10
padding.y = 10

[env]
term = "xterm-256color"

[font]
normal.family = "JetBrains Mono NL"
bold.family = "JetBrains Mono NL"
italic.family = "JetBrains Mono NL"
bold_italic.family = "JetBrains Mono NL"
size = 14.0

[scrolling]
history = 65535
multiplier = 1

#[debug]
#render_timer = true

# Colors (Gruvbox Material Dark Medium)
[colors.primary]
background = '#282828'
foreground = '#dfbf8e'

[colors.normal]
black   = '#665c54'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e78a4e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'

[colors.bright]
black   = '#928374'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#e3a84e'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#dfbf8e'
